version: "3"
services:
  jupyter:
    image: custom_extension
    container_name: custom_jupyter
    ports:
      - 8888:8888
    environment:
      - SERVER_HOSTNAME=localhost
      - KUBECONFIG=/Users/sahiljajodia/.kube/config
    volumes:
      - /Users/sahiljajodia/SWAN/switch-cluster/switch-cluster:/home/jovyan/switch-cluster
      - /Users/sahiljajodia/SWAN/switch-cluster/run.sh:/home/jovyan/run.sh
      - /Users/sahiljajodia/SWAN/switch-cluster/switch-cluster/node_modules:/home/jovyan/switch-cluster/node_modules
      - /Users/sahiljajodia/.kube/config:/Users/sahiljajodia/.kube/config
      - /Users/sahiljajodia/.minikube:/Users/sahiljajodia/.minikube
    entrypoint:
      - bash
      - -c
      - |
          # if true; then
            cd /home/jovyan/switch-cluster && \
            rm -rf ./switchcluster/js && \
            make && \
            pip install . && \
            jupyter nbextension install --py --system switchcluster
          # fi

          jupyter notebook --allow-root
volumes:
  home: