version: "3"
services:
  jupyter:
    image: custom_extension
    container_name: custom_jupyter
    hostname: swan-gsoc19
    ports:
      - 9999:8888
      - 5001:5001
      - 5002:5002
      - 5003:5003
    environment:
      - SERVER_HOSTNAME=localhost
      - KUBECONFIG=/home/jovyan/.kube/config
      - OS_TOKEN=${OS_TOKEN}
      - PYSPARK_PYTHON=/usr/bin/python2
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python2
    volumes:
      - /root/switch-cluster/switch-cluster:/home/jovyan/switch-cluster:Z
      - /root/switch-cluster/switch-cluster/run.sh:/home/jovyan/run.sh:Z
      - /root/switch-cluster/switch-cluster/node_modules:/home/jovyan/switch-cluster/node_modules:Z
      - /root/.kube/config:/home/jovyan/.kube/config:Z
      # - /Users/sahiljajodia/.minikube:/Users/sahiljajodia/.minikube
    entrypoint:
      - bash
      - -c
      - |
          conda create -n ipykernel_py2 python=2 ipykernel
          activate ipykernel_py2    
          python -m ipykernel install --user
          # if true; then
            cd /home/jovyan/switch-cluster && \
            rm -rf ./switchcluster/js && \
            make && \
            pip install . && \
            jupyter nbextension install --py --system switchcluster
          # fi

          jupyter notebook --allow-root
volumes:
  home: