version: "3"
services:
  jupyter:
    image: custom_extension
    container_name: custom_jupyter
    hostname: swan-gsoc19
    ports:
      - 9999:8888
      - 5001:5001
      - 5002:5002
      - 5003:5003
    environment:
      - USER=sjajodia
      - SERVER_HOSTNAME=localhost
#      - KUBECONFIG=/home/jovyan/.kube/config
      - OS_TOKEN=${OS_TOKEN}
    volumes:
      - /root/switch-cluster/switch-cluster:/home/jovyan/switch-cluster:Z
      - /root/switch-cluster/switch-cluster/run.sh:/home/jovyan/run.sh:Z
      - /root/switch-cluster/switch-cluster/node_modules:/home/jovyan/switch-cluster/node_modules:Z
      - /root/.kube/config:/home/jovyan/.kube/config:Z
    entrypoint:
      - bash
      - -c
      - |
        cd /home/jovyan/switch-cluster && \
        rm -rf ./switchcluster/js && \
        make && \
        pip install . && \
        jupyter nbextension install --py --system switchcluster && \
        jupyter notebook --allow-root
volumes:
  home: