version: "3"
services:
  jupyter:
    image: custom_extension
    container_name: custom_jupyter
    hostname: swan-gsoc19
    ports:
      - 9999:8888
      - 5001:5001
      - 5002:5002
      - 5003:5003
    environment:
      - USER=sjajodia
      - SERVER_HOSTNAME=localhost
#      - KUBECONFIG=/home/jovyan/.kube/config
      - OS_TOKEN=${OS_TOKEN}
    volumes:
      - /root/k8s-selection/k8s-selection:/home/jovyan/k8s-selection:Z
      - /root/k8s-selection/k8s-selection/run.sh:/home/jovyan/run.sh:Z
      - /root/k8s-selection/k8s-selection/node_modules:/home/jovyan/k8s-selection/node_modules:Z
      - /root/.kube:/home/jovyan/.kube:Z
    entrypoint:
      - bash
      - -c
      - |
        cd /home/jovyan/k8s-selection && \
        rm -rf ./k8sselection/js && \
        make && \
        pip install . && \
        jupyter nbextension install --py --system k8sselection && \
        jupyter notebook --allow-root
volumes:
  home: