version: "3"
services:
  jupyter:
    image: custom_extension
    container_name: custom_jupyter
    ports:
      - 9999:8888
      - 5201:5001
      - 5202:5002
      - 5203:5003
    environment:
      - SERVER_HOSTNAME=localhost
      - KUBECONFIG=/home/jovyan/.kube/config
      - OS_TOKEN=${OS_TOKEN}
    volumes:
      - /root/switch-cluster/switch-cluster:/home/jovyan/switch-cluster:Z
      - /root/switch-cluster/switch-cluster/run.sh:/home/jovyan/run.sh:Z
      - /root/switch-cluster/switch-cluster/node_modules:/home/jovyan/switch-cluster/node_modules:Z
      - /root/tutorial-keystone-creds/config:/home/jovyan/.kube/config:Z
      # - /Users/sahiljajodia/.minikube:/Users/sahiljajodia/.minikube
    entrypoint:
      - bash
      - -c
      - |
          # if true; then
            cd /home/jovyan/switch-cluster && \
            rm -rf ./switchcluster/js && \
            make && \
            pip install . && \
            jupyter nbextension install --py --system switchcluster
          # fi

          jupyter notebook --allow-root
volumes:
  home: