apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit-cluster-swan-sjajodia
  namespace: swan-sjajodia
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: sjajodia
